name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      
    - name: Install dependencies
      run: |
        go version
        go get gopkg.in/yaml.v2
        go get k8s.io/client-go@v12.0.0
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...
